/**
 * LinkedIn Posting Confirmation Routes
 *
 * Public endpoints — no authentication required.
 * These are hit by the employee from their browser after publishing on LinkedIn.
 *
 * Flow:
 *   Certificate email → "Share on LinkedIn" link
 *     → GET  /api/linkedin/confirm/:token   (confirmation UI page)
 *     → POST /api/linkedin/confirm/:token   (writes DB, returns JSON)
 */

const express = require("express");
const router = express.Router();
const Employee = require("../models/Employee");
const { logActivity } = require("../utils/auditLogger");

// ─── helpers ────────────────────────────────────────────────────────────────

/**
 * Decode the base64 token that was originally generated by buildLinkedInShareUrl.
 * Returns { employeeId, batchId } or throws on invalid input.
 */
function decodeToken(token) {
  try {
    const json = Buffer.from(token, "base64").toString("utf8");
    const parsed = JSON.parse(json);
    if (!parsed.employeeId || !parsed.batchId)
      throw new Error("Missing fields");
    return { employeeId: parsed.employeeId, batchId: parsed.batchId };
  } catch {
    throw new Error("Invalid confirmation token");
  }
}

// ─── GET /api/linkedin/confirm/:token ────────────────────────────────────────
// Serves the lightweight public confirmation page.
// The employee lands here automatically after the LinkedIn share page opens.
router.get("/confirm/:token", async (req, res) => {
  let employeeId = "";
  let employeeName = "there";

  try {
    const decoded = decodeToken(req.params.token);
    employeeId = decoded.employeeId;
    const emp = await Employee.findOne({
      employeeId: decoded.employeeId,
      batchId: decoded.batchId,
    }).lean();
    if (emp) {
      employeeName = emp.employeeName.split(" ")[0];

      // If already confirmed, show a "already recorded" page
      if (emp.linkedInPosted === true || emp.linkedinStatus === "POSTED") {
        return res
          .setHeader("Content-Type", "text/html; charset=utf-8")
          .send(buildAlreadyPostedPage(emp.employeeName));
      }
    }
  } catch {
    // If token is bad just show the generic page — POST will also validate
  }

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.send(buildConfirmationPage(req.params.token, employeeName));
});

// ─── POST /api/linkedin/confirm/:token ───────────────────────────────────────
// Called by the confirmation page when the employee clicks "Yes, I Posted".
// Updates MongoDB and returns JSON — the page reads the JSON and shows success UI.
router.post("/confirm/:token", async (req, res) => {
  try {
    const { employeeId, batchId } = decodeToken(req.params.token);

    const emp = await Employee.findOneAndUpdate(
      { employeeId, batchId },
      {
        linkedInPosted: true,
        linkedinStatus: "POSTED",
        postedAt: new Date(),
      },
      { returnDocument: "after" },
    ).lean();

    if (!emp) {
      return res
        .status(404)
        .json({ success: false, message: "Employee not found" });
    }

    // Audit log
    await logActivity({
      userName: emp.employeeName,
      action: `Marked LinkedIn posted for ${emp.employeeName}`,
      type: "linkedin",
      meta: {
        employeeId: emp.employeeId,
        batchId: emp.batchId,
        source: "self-confirm",
      },
    });

    console.log(
      `✓ LinkedIn self-confirmed: ${emp.employeeName} (${employeeId})`,
    );

    return res.json({ success: true, employeeName: emp.employeeName });
  } catch (err) {
    console.error("❌ LinkedIn confirm error:", err.message);
    return res.status(400).json({ success: false, message: err.message });
  }
});

// ─── HTML builders ───────────────────────────────────────────────────────────

function buildConfirmationPage(token, firstName) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Confirm LinkedIn Post</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Helvetica Neue',sans-serif;
       background:linear-gradient(135deg,#0f172a 0%,#1e1b4b 100%);
       min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}
  .card{background:#1e293b;border:1px solid #334155;border-radius:16px;
        max-width:460px;width:100%;padding:0;overflow:hidden;
        box-shadow:0 25px 50px rgba(0,0,0,.5)}
  .top{background:linear-gradient(135deg,#0077b5,#005885);padding:32px 32px 24px;text-align:center}
  .top .icon{font-size:48px;margin-bottom:12px}
  .top h1{color:#fff;font-size:22px;font-weight:700;margin-bottom:6px}
  .top p{color:rgba(255,255,255,.8);font-size:14px}
  .body{padding:32px}
  .question{color:#e2e8f0;font-size:17px;font-weight:600;text-align:center;margin-bottom:28px;line-height:1.5}
  .btn{width:100%;padding:14px 24px;border:none;border-radius:10px;font-size:16px;
       font-weight:700;cursor:pointer;transition:all .2s;display:flex;align-items:center;
       justify-content:center;gap:10px;margin-bottom:12px}
  .btn-yes{background:linear-gradient(135deg,#10b981,#059669);color:#fff}
  .btn-yes:hover:not(:disabled){background:linear-gradient(135deg,#059669,#047857);transform:translateY(-1px)}
  .btn-yes:active{transform:translateY(0)}
  .btn-no{background:#1e293b;color:#94a3b8;border:1px solid #334155;font-size:14px;padding:10px 24px}
  .btn-no:hover{background:#293548;color:#cbd5e1}
  .btn:disabled{opacity:.6;cursor:not-allowed;transform:none}
  .spinner{display:inline-block;width:18px;height:18px;border:2px solid rgba(255,255,255,.3);
           border-top-color:#fff;border-radius:50%;animation:spin .8s linear infinite}
  @keyframes spin{to{transform:rotate(360deg)}}
  .success-wrap{text-align:center;display:none}
  .success-wrap .check{font-size:56px;margin-bottom:16px}
  .success-wrap h2{color:#10b981;font-size:20px;font-weight:700;margin-bottom:8px}
  .success-wrap p{color:#94a3b8;font-size:14px;line-height:1.6}
  .error-box{background:#7f1d1d;border:1px solid #991b1b;color:#fca5a5;
             border-radius:8px;padding:12px 16px;font-size:13px;margin-top:12px;display:none;text-align:center}
  .note{color:#64748b;font-size:12px;text-align:center;margin-top:16px;line-height:1.5}
</style>
</head>
<body>
<div class="card">
  <div class="top">
    <div class="icon">🎉</div>
    <h1>Congratulations, ${firstName}!</h1>
    <p>Your achievement is worth sharing</p>
  </div>
  <div class="body">
    <div id="confirmView">
      <p class="question">Have you successfully published your LinkedIn post?</p>
      <button class="btn btn-yes" id="yesBtn" onclick="confirmPosted()">
        <span>✓</span> Yes, I Posted
      </button>
      <button class="btn btn-no" id="noBtn" onclick="notYet()">
        Not Yet
      </button>
      <div class="error-box" id="errorBox"></div>
      <p class="note">No account required · This just lets your team know you've shared your certificate</p>
    </div>
    <div class="success-wrap" id="successView">
      <div class="check">🏆</div>
      <h2>Recorded!</h2>
      <p>Your LinkedIn post has been confirmed.<br/>Your team has been notified — keep up the great work!</p>
    </div>
  </div>
</div>

<script>
const TOKEN = "${token}";

async function confirmPosted() {
  const yesBtn = document.getElementById("yesBtn");
  const noBtn  = document.getElementById("noBtn");
  const errBox = document.getElementById("errorBox");

  yesBtn.disabled = true;
  noBtn.disabled  = true;
  errBox.style.display = "none";
  yesBtn.innerHTML = '<span class="spinner"></span> Recording…';

  try {
    const resp = await fetch("/api/linkedin/confirm/" + TOKEN, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
    });
    const data = await resp.json();

    if (data.success) {
      document.getElementById("confirmView").style.display = "none";
      document.getElementById("successView").style.display = "block";
    } else {
      throw new Error(data.message || "Something went wrong");
    }
  } catch (err) {
    errBox.textContent = "❌ " + (err.message || "Could not record your post. Please try again.");
    errBox.style.display = "block";
    yesBtn.disabled = false;
    noBtn.disabled  = false;
    yesBtn.innerHTML = '<span>✓</span> Yes, I Posted';
  }
}

function notYet() {
  // Close the tab or show a friendly message
  const card = document.querySelector(".card .body");
  card.innerHTML = \`
    <div style="text-align:center;padding:8px 0">
      <div style="font-size:40px;margin-bottom:16px">💪</div>
      <p style="color:#e2e8f0;font-size:16px;font-weight:600;margin-bottom:8px">No worries!</p>
      <p style="color:#94a3b8;font-size:14px;line-height:1.6">
        Come back and click this link once you've posted.<br/>
        Your team is cheering you on!
      </p>
    </div>\`;
}
</script>
</body>
</html>`;
}

function buildAlreadyPostedPage(fullName) {
  const firstName = fullName.split(" ")[0];
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Already Confirmed</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
       background:linear-gradient(135deg,#0f172a,#1e1b4b);
       min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}
  .card{background:#1e293b;border:1px solid #334155;border-radius:16px;
        max-width:420px;width:100%;padding:40px 32px;text-align:center;
        box-shadow:0 25px 50px rgba(0,0,0,.5)}
  .icon{font-size:56px;margin-bottom:16px}
  h1{color:#10b981;font-size:20px;font-weight:700;margin-bottom:8px}
  p{color:#94a3b8;font-size:14px;line-height:1.6}
</style>
</head>
<body>
<div class="card">
  <div class="icon">✅</div>
  <h1>Already recorded, ${firstName}!</h1>
  <p>Your LinkedIn post confirmation was already saved.<br/>Your team appreciates you sharing your achievement!</p>
</div>
</body>
</html>`;
}

module.exports = router;
